import { environment } from '../../../environment';

export const API_BACKOFFICE = environment.apiUrl;

export const WALLET_ENV = API_BACKOFFICE + '/wallet';
export const WALLET_ENV_PAGE = WALLET_ENV + '/list';



export const ACCOUNT_USER = API_BACKOFFICE + '/user';
export const ACCOUNT_USER_USER = ACCOUNT_USER + '/user';
export const ACCOUNT_USER_REGISTER_BO = ACCOUNT_USER + '/registration';
export const ACCOUNT_USER_PUBLIC = API_BACKOFFICE + "/public";
export const ACCOUNT_USER_PUBLIC_LOGIN = ACCOUNT_USER_PUBLIC + "/login";
export const ACCOUNT_USER_PUBLIC_REGISTRATION = ACCOUNT_USER_PUBLIC + "/registration";
export const ACCOUNT_USER_ROLE = API_BACKOFFICE + '/user/role';
export const ACCOUNT_USER_ROLE_STORE = ACCOUNT_USER_ROLE;
export const ACCOUNT_USER_ROLE_PAGE = ACCOUNT_USER_ROLE;
export const ACCOUNT_USER_ROLE_UPDATE = ACCOUNT_USER_ROLE;
export const ACCOUNT_USER_ROLE_TASK_TREE = API_BACKOFFICE + '/user/role-task-tree';
export const ACCOUNT_USER_ROLE_TASK_TREE_ACTIVATED = ACCOUNT_USER_ROLE_TASK_TREE + '/activated';
export const ACCOUNT_USER_TASK = ACCOUNT_USER + '/task';
export const ACCOUNT_USER_TASK_PAGE = ACCOUNT_USER_TASK;
export const ACCOUNT_USER_TASK_STORE = ACCOUNT_USER_TASK;
export const ACCOUNT_USER_TASK_UPDATE = ACCOUNT_USER_TASK;

export const COMMON_LOCATION = API_BACKOFFICE + '/location';

export const COMMON_LOCATION_CITY = COMMON_LOCATION + '/city';
export const COMMON_LOCATION_CITY_STORE = COMMON_LOCATION_CITY + '/add';
export const COMMON_LOCATION_CITY_PAGE = COMMON_LOCATION_CITY + '/list';
export const COMMON_LOCATION_CITY_DETAIL = COMMON_LOCATION_CITY + '/detail';
export const COMMON_LOCATION_CITY_UPDATE = COMMON_LOCATION_CITY + '/update';

export const COMMON_LOCATION_PROVINCE = COMMON_LOCATION + '/province';
export const COMMON_LOCATION_PROVINCE_STORE = COMMON_LOCATION_PROVINCE + '/add';
export const COMMON_LOCATION_PROVINCE_PAGE = COMMON_LOCATION_PROVINCE + '/list';
export const COMMON_LOCATION_PROVINCE_DETAIL = COMMON_LOCATION_PROVINCE + '/detail';
export const COMMON_LOCATION_PROVINCE_UPDATE = COMMON_LOCATION_PROVINCE + '/update';

export const COMMON_LOCATION_COUNTRY = COMMON_LOCATION + '/country';
export const COMMON_LOCATION_COUNTRY_STORE = COMMON_LOCATION_COUNTRY + '/add';
export const COMMON_LOCATION_COUNTRY_PAGE = COMMON_LOCATION_COUNTRY + '/list';
export const COMMON_LOCATION_COUNTRY_DETAIL = COMMON_LOCATION_COUNTRY + '/detail';
export const COMMON_LOCATION_COUNTRY_UPDATE = COMMON_LOCATION_COUNTRY + '/update';
export const ORGANIZATION = API_BACKOFFICE + '/organization';
export const ORGANIZATION_COMPANY = ORGANIZATION + "/company";
export const ORGANIZATION_COMPANY_PAGE = ORGANIZATION_COMPANY + "/page";
export const ORGANIZATION_COMPANY_INFO = ORGANIZATION + "/company_info";
export const ORGANIZATION_COMPANY_INFO_DETAIL = ORGANIZATION_COMPANY_INFO + "/detail";
export const ORGANIZATION_COMPANY_ADDRESS = ORGANIZATION + "/company_address";
export const ORGANIZATION_COMPANY_ADDRESS_DETAIL = ORGANIZATION_COMPANY_ADDRESS + "/detail"
export const COMMON_ORGANIZATION = API_BACKOFFICE + '/common/organization';
export const COMMON_ORGANIZATION_TENANT = COMMON_ORGANIZATION + '/tenant';
export const COMMON_ORGANIZATION_TENANT_STORE = COMMON_ORGANIZATION_TENANT + '/store';
export const COMMON_ORGANIZATION_TENANT_PAGE = COMMON_ORGANIZATION_TENANT + '/page';
export const COMMON_ORGANIZATION_TENANT_UPDATE = COMMON_ORGANIZATION_TENANT + '/update';

export const COMMON_LOCATION_CONTINENTAL = COMMON_LOCATION + '/continent';
export const COMMON_LOCATION_CONTINENTAL_STORE = COMMON_LOCATION_CONTINENTAL + '/add';
export const COMMON_LOCATION_CONTINENTAL_PAGE = COMMON_LOCATION_CONTINENTAL + '/list';
export const COMMON_LOCATION_CONTINENTAL_DETAIL = COMMON_LOCATION_CONTINENTAL + '/detail';
export const COMMON_LOCATION_CONTINENTAL_UPDATE = COMMON_LOCATION_CONTINENTAL + '/update';

export const COMMON_AIRLINE = API_BACKOFFICE + '/airline';

export const COMMON_AIRLINE_AIRLINE = COMMON_AIRLINE + "/airline";
export const COMMON_AIRLINE_AIRLINE_STORE = COMMON_AIRLINE_AIRLINE;
export const COMMON_AIRLINE_AIRLINE_PAGE = COMMON_AIRLINE_AIRLINE;
export const COMMON_AIRLINE_AIRLINE_UPDATE = COMMON_AIRLINE_AIRLINE + '/update';

export const COMMON_CORE = API_BACKOFFICE + '/common/core';
export const COMMON_CORE_ATTRIBUTE = COMMON_CORE + '/attribute';
export const COMMON_CORE_ATTRIBUTE_STORE = COMMON_CORE_ATTRIBUTE;
export const COMMON_CORE_ATTRIBUTE_PAGE = COMMON_CORE_ATTRIBUTE;
export const COMMON_CORE_ATTRIBUTE_UPDATE = COMMON_CORE_ATTRIBUTE + '/update';

export const COMMON_CORE_CHANNEL = COMMON_CORE + '/channel';
export const COMMON_CORE_CHANNEL_STORE = COMMON_CORE_CHANNEL + '/store';
export const COMMON_CORE_CHANNEL_PAGE = COMMON_CORE_CHANNEL + '/page';
export const COMMON_CORE_CHANNEL_UPDATE = COMMON_CORE_CHANNEL + '/update';
export const COMMON_CORE_CHANNEL_DETAIL = COMMON_CORE_CHANNEL + '/detail';

export const COMMON_PAYMENT = API_BACKOFFICE + '/payment';

export const COMMON_PAYMENT_BANK = COMMON_PAYMENT + '/bank';
export const COMMON_PAYMENT_BANK_STORE = COMMON_PAYMENT_BANK;
export const COMMON_PAYMENT_BANK_PAGE = COMMON_PAYMENT_BANK;
export const COMMON_PAYMENT_BANK_UPDATE = COMMON_PAYMENT_BANK;

export const COMMON_PRODUCT = API_BACKOFFICE + "/product";

export const COMMON_PRODUCT_TYPE = COMMON_PRODUCT + "/type";
export const COMMON_PRODUCT_TYPE_STORE = COMMON_PRODUCT_TYPE;
export const COMMON_PRODUCT_TYPE_PAGE = COMMON_PRODUCT_TYPE;
export const COMMON_PRODUCT_TYPE_UPDATE = COMMON_PRODUCT_TYPE;

export const COMMON_PRODUCT_CATEGORY = COMMON_PRODUCT + "/category";
export const COMMON_PRODUCT_CATEGORY_STORE = COMMON_PRODUCT_CATEGORY;
export const COMMON_PRODUCT_CATEGORY_PAGE = COMMON_PRODUCT_CATEGORY;
export const COMMON_PRODUCT_CATEGORY_UPDATE = COMMON_PRODUCT_CATEGORY;

export const COMMON_PRODUCT_PRODUCT = COMMON_PRODUCT + "/category";
export const COMMON_PRODUCT_PRODUCT_STORE = COMMON_PRODUCT_PRODUCT + '/add';
export const COMMON_PRODUCT_PRODUCT_PAGE = COMMON_PRODUCT_PRODUCT + '/list';
export const COMMON_PRODUCT_PRODUCT_UPDATE = COMMON_PRODUCT_PRODUCT + '/update';

export const COMMON_PAYMENT_BANKBIN = COMMON_PAYMENT + '/bank_bin';
export const COMMON_PAYMENT_BANKBIN_STORE = COMMON_PAYMENT_BANKBIN + '/store';
export const COMMON_PAYMENT_BANKBIN_PAGE = COMMON_PAYMENT_BANKBIN + '/page';
export const COMMON_PAYMENT_BANKBIN_UPDATE = COMMON_PAYMENT_BANKBIN + '/update';
export const COMMON_PAYMENT_BANKMETHOD = COMMON_PAYMENT + '/bank_method';
export const COMMON_PAYMENT_BANKMETHOD_STORE = COMMON_PAYMENT_BANKMETHOD;
export const COMMON_PAYMENT_BANKMETHOD_PAGE = COMMON_PAYMENT_BANKMETHOD;
export const COMMON_PAYMENT_BANKMETHOD_UPDATE = COMMON_PAYMENT_BANKMETHOD;
export const COMMON_LOCATION_AIRPORT = COMMON_AIRLINE + '/airport';
export const COMMON_LOCATION_AIRPORT_STORE = COMMON_LOCATION_AIRPORT;
export const COMMON_LOCATION_AIRPORT_PAGE = COMMON_LOCATION_AIRPORT;
export const COMMON_LOCATION_AIRPORT_DETAIL = COMMON_LOCATION_AIRPORT;
export const COMMON_LOCATION_AIRPORT_UPDATE = COMMON_LOCATION_AIRPORT;
export const COMMON_LOCATION_VILLAGE = COMMON_LOCATION + '/village';
export const COMMON_LOCATION_VILLAGE_STORE = COMMON_LOCATION_VILLAGE + '/add';
export const COMMON_LOCATION_VILLAGE_PAGE = COMMON_LOCATION_VILLAGE + '/list';
export const COMMON_LOCATION_VILLAGE_DETAIL = COMMON_LOCATION_VILLAGE + '/detail';
export const COMMON_LOCATION_VILLAGE_UPDATE = COMMON_LOCATION_VILLAGE + '/update';
export const COMMON_LOCATION_SUBDISTRICT = COMMON_LOCATION + '/subDistrict';
export const COMMON_LOCATION_SUBDISTRICT_STORE = COMMON_LOCATION_SUBDISTRICT + '/add';
export const COMMON_LOCATION_SUBDISTRICT_PAGE = COMMON_LOCATION_SUBDISTRICT + '/list';
export const COMMON_LOCATION_SUBDISTRICT_DETAIL = COMMON_LOCATION_SUBDISTRICT + '/detail';
export const COMMON_LOCATION_SUBDISTRICT_UPDATE = COMMON_LOCATION_SUBDISTRICT + '/update';

export const RECONCILE_RECONCILE = API_BACKOFFICE + '/reconcile';
export const RECONCINCILE_RECONCILE_SALES_PAGE = RECONCILE_RECONCILE + '/page';
export const RECONCINCILE_RECONCILE_PAYMENT_PAGE = RECONCILE_RECONCILE + '/page';
export const RECONCINCILE_RECONCILE_DEPOSIT_PAGE = RECONCILE_RECONCILE + '/page';